export const TEXTS = {
  headerTitle: 'Rick and Morty Explorer',
  searchPlaceholder: 'SearchPage characters by name...',
  searchButton: 'Search',
  resultsTitle: 'Results',
  noResults: 'No results found.',
  noCharacter: 'Character not found',
  errorPrefix: 'Error:',
  fallbackTitle: 'Something went wrong.',
  tryAgain: 'Try again',
  aboutLink: 'About',
  aboutTitle: 'About this App',
  author: 'Author:',
  authorName: ' Tati Lebedeva',
  aboutText:
    'This project is a React SPA for exploring characters from the Rick and Morty universe.',
  learnMore: 'Learn more about',
  rsSchool: 'RS School React Course',
  restApi: 'REST API',
  rickApi: 'The Rick and Morty API',
  backToHome: 'Back to Home',
  status: 'Status:',
  species: 'Species:',
  type: 'Type:',
  gender: 'Gender:',
  origin: 'Origin:',
  location: 'Location:',
  created: 'Created:',
  caughtError: 'ErrorBoundary caught an error:',
  pagination: (page: number, totalPages: number) =>
    `Page ${page} of ${totalPages}`,
  notExist: 'Sorry, the page you’re looking for doesn’t exist.',
  notFoundTitle: '404',
  hello: 'Hello, ',
  toggleTheme: 'Toggle theme',
  download: 'Download',
  unselectAll: 'Unselect all',
  bye: 'Bye!',
  itemSelected: (count: number) =>
    `${count} ${count === 1 ? 'item' : 'items'} selected`,
};
